In [1]:
from read_graph import GraphDataset

/Users/joseperezcano/Desktop/CFIS Quinto Curso/TFG/pulmon/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
gd = GraphDataset(node_dir = '../../Data/train/graphs/', max_degree = 10, max_dist = 200)

In [8]:
gd.node_names[1]

'(H&E), VH22B003587A012001 (x=27625.0, y=56085.0, w=1024.0, h=1024.0)'

In [9]:
import networkx as nx
import dgl
k = 1
g = gd[k]
nx.write_gml(dgl.to_networkx(g), gd.node_names[k] + '.gml')

In [14]:
import torch
model = torch.nn.Sequential(torch.nn.Linear(3,3))
type(torch.optim.Adam(model.parameters(), lr=0.001))

torch.optim.adam.Adam

In [5]:
g.edges()

(tensor([  0,   0,   0,  ..., 343, 343, 343]),
 tensor([13,  7, 24,  ..., 92, 80, 72]))

In [6]:
g.edata['dist']

tensor([[31.0000],
        [61.6847],
        [64.4748],
        ...,
        [60.8769],
        [61.1310],
        [71.3092]])

In [5]:
import sys
import os

PKG_DIR = os.path.dirname(os.path.dirname('./'))
sys.path.append(PKG_DIR)

In [6]:
from utils.nearest import generate_tree

In [7]:
tree = generate_tree(zip([1,2,3,4], [3,56,3,2,]))

In [10]:
tree.query([4,3], k=5)

(array([ 1.        ,  1.        ,  3.        , 53.03772242,         inf]),
 array([3, 2, 0, 1, 4]))

In [9]:
tree.data

array([[ 1.,  3.],
       [ 2., 56.],
       [ 3.,  3.],
       [ 4.,  2.]])

In [19]:
from itertools import tee

dists = [1,2,3,4]
idx = [1,5,2,5]
tmp = list(filter(lambda x: x[1] < 3, zip(dists, idx)))
print(tmp)
tmp1, tmp2 = tee(tmp)
aux1, aux2 = list(x[0] for x in tmp1), list(x[1] for x in tmp2)
len(aux1)

[(1, 1), (3, 2)]


2